[package]
name = "wikitest"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = "0.5.0"
fancy-regex = "0.14.0"
quick-xml = "=0.24.1"
regex = "1.11.1"
reqwest = { version = "0.12.11", features = ["blocking"] }
rusqlite = "0.32.1"
scraper = "0.22.0"
